name: NodeJS with Webpack

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 16.19
      uses: actions/setup-node@v3
      with:
        node-version: 16.19
    # 配置依赖缓存
    - name: build
#    - uses: actions/cache@3
#      id: yarn-cache
#      with:
#        path: ${{ steps.yarn-cahce-dir-path.outputs.dir }}
#        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-yarn-
      run: yarn install && npm run build && pwd
    - name: package use github actions
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        name: case-workbench-front
        path: ./dist
    - name: deploy to github pages
      uses: actions/deploy-pages@v1.2.4
      with:
        artifact_name: case-workbench-front

